package app.forge.fitness.data.db

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import app.forge.domain.model.BodyMetricKind
import app.forge.domain.model.Equipment
import app.forge.domain.model.ExerciseCategory
import app.forge.domain.model.LogType
import app.forge.domain.model.Muscle
import app.forge.domain.model.SessionStatus
import app.forge.domain.model.SetType
import kotlinx.serialization.Serializable

/*
 * Conventions for every table:
 *  - `id` is a random UUID string, so backups from different devices merge without clashes.
 *  - `createdAt` / `updatedAt` are epoch milliseconds; `updatedAt` decides which copy wins
 *    when merging backups.
 *  - `deletedAt` marks a soft delete. Rows are hidden, not removed, so deletes can be
 *    undone and are carried through backups.
 *  - Weights are always stored in kilograms.
 */

@Entity(
    tableName = "exercise",
    indices = [Index("name"), Index("sourceId", unique = true)],
)
@Serializable
data class ExerciseEntity(
    @PrimaryKey val id: String,
    val name: String,
    val primaryMuscles: List<Muscle>,
    val secondaryMuscles: List<Muscle>,
    val equipment: Equipment?,
    val category: ExerciseCategory,
    /** Which fields a set row shows (weight × reps, reps, time, distance + time). */
    val logType: LogType,
    /** [app.forge.domain.bodyweight.BodyweightProfile] name for bodyweight moves (v2). */
    val bodyweightProfile: String? = null,
    /** Bench/box height for incline and decline moves, in cm (v2). */
    val bodyweightElevationCm: Double? = null,
    /** [app.forge.domain.dataset.HomePack.Chain] name and position in it (v2). */
    val progressionChain: String? = null,
    val progressionStep: Int? = null,
    val mechanic: String?,
    val force: String?,
    val level: String?,
    val instructions: List<String>,
    val images: List<String>,
    val isCustom: Boolean,
    /** ID in the bundled dataset (null for exercises you create yourself). */
    val sourceId: String?,
    @ColumnInfo(defaultValue = "0") val archived: Boolean = false,
    val createdAt: Long,
    val updatedAt: Long,
    val deletedAt: Long? = null,
)

@Entity(
    tableName = "workout_session",
    indices = [Index("startedAt"), Index("status")],
)
@Serializable
data class WorkoutSessionEntity(
    @PrimaryKey val id: String,
    val name: String,
    val routineId: String?,
    val startedAt: Long,
    val endedAt: Long?,
    val status: SessionStatus,
    val notes: String?,
    val bodyweightKg: Double?,
    val createdAt: Long,
    val updatedAt: Long,
    val deletedAt: Long? = null,
    /** Generated by "Load demo data" (v4); removed by "Remove demo data". */
    @ColumnInfo(defaultValue = "0") val isDemo: Boolean = false,
    /** Average and peak heart rate from your watch/strap via Health Connect (v5). */
    val avgHeartRate: Int? = null,
    val maxHeartRate: Int? = null,
)

@Entity(
    tableName = "session_exercise",
    foreignKeys = [
        ForeignKey(
            entity = WorkoutSessionEntity::class,
            parentColumns = ["id"],
            childColumns = ["sessionId"],
            onDelete = ForeignKey.CASCADE,
        ),
        ForeignKey(
            entity = ExerciseEntity::class,
            parentColumns = ["id"],
            childColumns = ["exerciseId"],
            onDelete = ForeignKey.RESTRICT,
        ),
    ],
    indices = [Index("sessionId"), Index("exerciseId")],
)
@Serializable
data class SessionExerciseEntity(
    @PrimaryKey val id: String,
    val sessionId: String,
    val exerciseId: String,
    val position: Int,
    /** Exercises in the same session that share a group number form a superset. */
    val supersetGroup: Int?,
    val notes: String?,
    val restSeconds: Int?,
    val createdAt: Long,
    val updatedAt: Long,
    val deletedAt: Long? = null,
    /** Targets copied from the routine this workout was started from (v3). */
    val targetSets: Int? = null,
    /** Target reps (or seconds for timed exercises), e.g. 8 and 12 for "8–12". */
    val targetMin: Int? = null,
    val targetMax: Int? = null,
    val targetRpe: Double? = null,
)

@Entity(
    tableName = "set_entry",
    foreignKeys = [
        ForeignKey(
            entity = SessionExerciseEntity::class,
            parentColumns = ["id"],
            childColumns = ["sessionExerciseId"],
            onDelete = ForeignKey.CASCADE,
        ),
    ],
    indices = [Index("sessionExerciseId"), Index("completedAt")],
)
@Serializable
data class SetEntryEntity(
    @PrimaryKey val id: String,
    val sessionExerciseId: String,
    val position: Int,
    val type: SetType,
    val weightKg: Double?,
    val reps: Int?,
    val rpe: Double?,
    val durationSeconds: Int?,
    val distanceMeters: Double?,
    /** Null until the set is ticked off. */
    val completedAt: Long?,
    /**
     * What you actually moved per rep, in kg (v2): the weight for normal lifts, or your
     * bodyweight share + added weight for calisthenics. Worked out when the set is
     * ticked off, using that day's bodyweight, so old workouts never change.
     */
    val loadKg: Double? = null,
    val createdAt: Long,
    val updatedAt: Long,
    val deletedAt: Long? = null,
)

/**
 * A training program: routines that rotate in order on your training days (v3).
 * [trainingDays] is a bit set, Monday = bit 0 … Sunday = bit 6; 0 = any day.
 */
@Entity(tableName = "program")
@Serializable
data class ProgramEntity(
    @PrimaryKey val id: String,
    val name: String,
    val description: String?,
    /** Which prebuilt template it came from, if any. */
    val templateKey: String?,
    val trainingDays: Int,
    val isActive: Boolean,
    val createdAt: Long,
    val updatedAt: Long,
    val deletedAt: Long? = null,
)

/** A saved workout plan you can start with one tap (v3). */
@Entity(tableName = "routine", indices = [Index("programId")])
@Serializable
data class RoutineEntity(
    @PrimaryKey val id: String,
    val name: String,
    val notes: String?,
    /** Optional grouping in the routines list. */
    val folder: String?,
    /** Order in your routines list. */
    val position: Int,
    /** Set when the routine belongs to a program; [programPosition] is its turn in the rotation. */
    val programId: String?,
    val programPosition: Int?,
    val createdAt: Long,
    val updatedAt: Long,
    val deletedAt: Long? = null,
)

/** One exercise in a routine, with its targets (v3). */
@Entity(
    tableName = "routine_exercise",
    foreignKeys = [
        ForeignKey(
            entity = RoutineEntity::class,
            parentColumns = ["id"],
            childColumns = ["routineId"],
            onDelete = ForeignKey.CASCADE,
        ),
        ForeignKey(
            entity = ExerciseEntity::class,
            parentColumns = ["id"],
            childColumns = ["exerciseId"],
            onDelete = ForeignKey.RESTRICT,
        ),
    ],
    indices = [Index("routineId"), Index("exerciseId")],
)
@Serializable
data class RoutineExerciseEntity(
    @PrimaryKey val id: String,
    val routineId: String,
    val exerciseId: String,
    val position: Int,
    val supersetGroup: Int?,
    val targetSets: Int,
    /** Reps, or seconds for timed exercises. */
    val targetMin: Int?,
    val targetMax: Int?,
    val targetRpe: Double?,
    /** Null = your default rest time. */
    val restSeconds: Int?,
    val notes: String?,
    val createdAt: Long,
    val updatedAt: Long,
    val deletedAt: Long? = null,
)

/** One measurement on one day: bodyweight, waist, etc. (v2). */
@Serializable
@Entity(tableName = "body_metric", indices = [Index("kind", "measuredAt")])
data class BodyMetricEntity(
    @PrimaryKey val id: String,
    val kind: BodyMetricKind,
    /** Kilograms for weight, centimetres for lengths, percent for body fat. */
    val value: Double,
    val measuredAt: Long,
    val note: String? = null,
    val createdAt: Long,
    val updatedAt: Long,
    val deletedAt: Long? = null,
    @ColumnInfo(defaultValue = "0") val isDemo: Boolean = false,
)

/**
 * A progress photo (v4). The image lives in the app's private storage as
 * [fileName]; it never leaves your phone unless you back it up.
 */
@Serializable
@Entity(tableName = "progress_photo", indices = [Index("takenAt")])
data class ProgressPhotoEntity(
    @PrimaryKey val id: String,
    val takenAt: Long,
    val fileName: String,
    /** "Front", "Side", "Back" or null. */
    val pose: String?,
    val note: String?,
    val createdAt: Long,
    val updatedAt: Long,
    val deletedAt: Long? = null,
)

/**
 * A sport, cardio or mobility session (v5): logged by hand or imported from Health
 * Connect (e.g. a run your Amazfit strap recorded through Zepp).
 */
@Serializable
@Entity(
    tableName = "activity_session",
    indices = [Index("startedAt"), Index("externalId", unique = true)],
)
data class ActivitySessionEntity(
    @PrimaryKey val id: String,
    /** [app.forge.domain.activity.Sport] name. */
    val sport: String,
    /** Optional name, e.g. "Saturday match" or the title from Zepp. */
    val title: String? = null,
    val startedAt: Long,
    val durationMinutes: Int,
    /** Effort on a 1–10 scale. */
    val intensity: Int,
    val distanceMeters: Double? = null,
    val calories: Double? = null,
    val avgHeartRate: Int? = null,
    val maxHeartRate: Int? = null,
    val notes: String? = null,
    /** [ActivitySource] name. */
    val source: String = ActivitySource.MANUAL.name,
    /** Health Connect record ID, so re-syncing never imports the same session twice. */
    val externalId: String? = null,
    val createdAt: Long,
    val updatedAt: Long,
    val deletedAt: Long? = null,
    @ColumnInfo(defaultValue = "0") val isDemo: Boolean = false,
)

val ActivitySessionEntity.endedAt: Long get() = startedAt + durationMinutes * 60_000L

enum class ActivitySource { MANUAL, HEALTH_CONNECT }

/**
 * One day of watch/strap data from Health Connect (v5). Re-synced, never edited by
 * hand, so it has no soft delete. [sleepMinutes], [hrvMs] are for the night *before*
 * [epochDay] (i.e. what you woke up with).
 */
@Serializable
@Entity(tableName = "daily_health")
data class DailyHealthEntity(
    @PrimaryKey val epochDay: Long,
    val steps: Long? = null,
    val sleepMinutes: Int? = null,
    val restingHr: Double? = null,
    val hrvMs: Double? = null,
    val updatedAt: Long,
)

/**
 * A food (v6). Nutrition values are per 100 g (or 100 ml), as on labels. Comes from
 * Open Food Facts (cached after the first lookup, so it works offline) or is entered
 * by you.
 */
@Serializable
@Entity(tableName = "food", indices = [Index("name"), Index("barcode", unique = true)])
data class FoodEntity(
    @PrimaryKey val id: String,
    val name: String,
    val brand: String? = null,
    val barcode: String? = null,
    val kcal: Double,
    val proteinG: Double,
    val carbsG: Double,
    val fatG: Double,
    val fiberG: Double? = null,
    val sugarG: Double? = null,
    val saltG: Double? = null,
    /** Grams in one serving, e.g. 30 for "1 bar (30 g)". */
    val servingG: Double? = null,
    val servingLabel: String? = null,
    /** [FoodSource] name. */
    val source: String = FoodSource.CUSTOM.name,
    @ColumnInfo(defaultValue = "0") val favorite: Boolean = false,
    val createdAt: Long,
    val updatedAt: Long,
    val deletedAt: Long? = null,
)

/**
 * GENERIC: the bundled Australian food database (AUSNUT 2023). FATSECRET: FatSecret's
 * database. WEB: read from a nutrition page on the web.
 */
enum class FoodSource { OPEN_FOOD_FACTS, CUSTOM, GENERIC, FATSECRET, WEB }

/**
 * One thing you ate (v6). The nutrition totals are copied in when you log it, so
 * editing a food later never rewrites what you've already eaten.
 */
@Serializable
@Entity(tableName = "food_log", indices = [Index("epochDay"), Index("foodId")])
data class FoodLogEntity(
    @PrimaryKey val id: String,
    /** Null for a quick add (just calories/macros). */
    val foodId: String? = null,
    val name: String,
    val epochDay: Long,
    /** [app.forge.domain.nutrition.Meal] name. */
    val meal: String,
    /** Amount eaten in grams; null for a quick add. */
    val grams: Double? = null,
    val kcal: Double,
    val proteinG: Double,
    val carbsG: Double,
    val fatG: Double,
    val fiberG: Double? = null,
    val sugarG: Double? = null,
    val saltG: Double? = null,
    val loggedAt: Long,
    val createdAt: Long,
    val updatedAt: Long,
    val deletedAt: Long? = null,
    @ColumnInfo(defaultValue = "0") val isDemo: Boolean = false,
)

/** A goal (v7): weekly workouts, a bodyweight, a lift, reps in a set, or protein days. */
@Serializable
@Entity(tableName = "goal")
data class GoalEntity(
    @PrimaryKey val id: String,
    /** [app.forge.domain.goals.GoalKind] name. */
    val kind: String,
    val target: Double,
    /** For strength and reps goals. */
    val exerciseId: String? = null,
    /** Where you started (bodyweight goals measure progress from here). */
    val startValue: Double? = null,
    /** When it was first reached (one-off goals only). */
    val reachedAt: Long? = null,
    val createdAt: Long,
    val updatedAt: Long,
    val deletedAt: Long? = null,
)

/** A daily habit (v7). Auto kinds tick themselves from your data. */
@Serializable
@Entity(tableName = "habit")
data class HabitEntity(
    @PrimaryKey val id: String,
    /** [app.forge.domain.goals.HabitKind] name. */
    val kind: String,
    val name: String,
    /** Steps or hours for auto habits that need a number. */
    val target: Double? = null,
    /** Days it's due ([app.forge.domain.goals.DayMask] bits, Monday = bit 0). */
    @ColumnInfo(defaultValue = "127") val dayMask: Int = 127,
    /** Reminder time as minutes after midnight, or null for none. */
    val reminderMinutes: Int? = null,
    val position: Int = 0,
    val createdAt: Long,
    val updatedAt: Long,
    val deletedAt: Long? = null,
)

/** A tick on a custom habit for one day (v7). Unticking deletes the row. */
@Serializable
@Entity(
    tableName = "habit_check",
    primaryKeys = ["habitId", "epochDay"],
    indices = [Index("epochDay")],
)
data class HabitCheckEntity(
    val habitId: String,
    val epochDay: Long,
    val checkedAt: Long,
)

/** One live heart-rate reading during a Forge workout, from your strap (v8). */
@Serializable
@Entity(tableName = "heart_rate_sample", primaryKeys = ["sessionId", "atMillis"])
data class HeartRateSampleEntity(
    val sessionId: String,
    val atMillis: Long,
    val bpm: Int,
)

/** Small key/value table for app bookkeeping, e.g. which exercise dataset is loaded. */
@Entity(tableName = "app_meta")
@Serializable
data class AppMetaEntity(
    @PrimaryKey val key: String,
    val value: String,
)
